### ISSUE TITLE
Bungeecord Error

### ISSUE THREAD

**Issue by Hellohi3654** [ofunny/BedrockPlayerManager#5]
[07:54:01 WARN]: Error enabling plugin BedrockPlayerManager
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_282]
at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_282]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_282]
at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_282]
at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_282]
at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_282]
at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_282]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_282]
at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_282]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_282]
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:44) ~[server.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:72c234b:unknown]
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[server.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:72c234b:unknown]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:381) ~[server.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:72c234b:unknown]
at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:285) ~[server.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:72c234b:unknown]
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:297) ~[server.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:72c234b:unknown]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49) ~[server.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:72c234b:unknown]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:72c234b:unknown]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63) ~[server.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:72c234b:unknown]
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[server.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:72c234b:unknown]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
... 18 more

I am using Flamecord 
The latest version of Geyser and Floodgate 1.0 doesn't look like a Floodgate or Geyser error though

**Comment by ofunny** [comment]
Hi,
Bedrock player manager has to be installed on each Spigot/Paper server, it is not a bungee plugin.
Follow the guide on https://ofunny.world/bedrock-player-manager/#howto
(2. Bungee, Waterfall and Velocity networks)

Install Geyser + Floodgate on Bungee/Waterfall
Install Floodgate + BedrockPlayerManager on each Spigot/Paper server.
Don't forget to copy the keys!
